### ISSUE TITLE
quantities of ingredients are missing

### ISSUE THREAD

**Issue by dmbrownlee** [EvaWest/Cook-book#3]
For example, instead of "tomato paste", you should have "15oz tomato paste".

**Comment by EvaWest** [comment]
Can we create a table?  Quantity should be in a separate column.

**Comment by dmbrownlee** [comment]
Since it is text, let's use the tab key.

**Comment by dmbrownlee** [comment]
Fixed in b0f3cf1b225f845179bd526df75295209788c4d0
